services:
  - type: web
    name: lovely-portfolio
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: PORT
        value: "10000"